@startuml usecase
left to right direction

rectangle "Update user data in database" {
    usecase interaction as "Update user data"
    usecase crud as "CRUD action" <<interface>>
    interaction <|.. crud : Extends
    usecase display as "Display data to user"
    display <|.. crud: Extends
}

actor User as "System user"

display -- User
User -- interaction
@enduml