@startuml usecase
left to right direction

rectangle "Gebruiker data updaten in de database" {
    usecase interaction as "Update gebruiker in database"
    usecase crud as "CRUD actie" <<interface>>
    interaction <|- crud : Extends
    usecase display as "Weergeef data aan gebruiker"
}

actor User as "Systeemgebruiker"

display -- User
User -- interaction
@enduml