@startuml usecase
left to right direction
skinparam linetype ortho

actor caller as "Caller"

note top of caller: Can be human or CircleCI

rectangle "Start tests" {
    usecase start as "Call framework"
    usecase search as "Search files for test classes
    --No test classes found:--
    Throw error"
    usecase db as "Start local test database"
    usecase init as "Fill database with dummy data"
    usecase servers as "Start server docker images"
    usecase load as "Load the test classes"
    usecase execute as "Execute test classes"
    usecase return as "Return test results"
    usecase error as "Display error "No testcases found""
}

caller -- start
search -> error

start -> search
search -> db
db -> init
start -> servers
servers --> load
init --> load
load -> execute
execute -> return
return --> caller

@enduml