@startuml Component diagram
skinparam Linetype ortho
skinparam componentStyle uml1
left to right direction

together {
    component "Web API" <<Code repository>> as web_api {
        component ":Test cases" as test_cases
        component ":Web server" <<Apache>> as api_server
        component ":Source code" as source
    }

    component "Functional testing framework" <<Composer package>> as framework {
        component ":Test runner" as runner
        component ":Test batch manager" as manager
        component ":Test database" <<SQLite>> as test_db
        interface "Database connection" as sqlite_conn
        interface "Spawn batch tester" as spawn
    }
}

component "bouw7" <<Code repository>> as bouw7 {
    component "Database migrations" as migrations
}

interface "Pull request" <<SSH>> as bouw7_pull
interface "API endpoints" <<HTTPS>> as endpoints
interface "Available tests" as tests

bouw7 -- bouw7_pull
runner -( bouw7_pull

endpoints -- api_server
framework .( endpoints

tests -- test_cases
tests ). runner

api_server .> source

sqlite_conn - test_db
runner ..( sqlite_conn

spawn - manager
runner .( spawn
@enduml