@startuml Component diagram
skinparam Linetype ortho
skinparam componentStyle uml1
left to right direction

together {
    component "Web API" <<Code repository>> as web_api {
        component ":Test cases" <<PHP class>> as test_cases
        component ":Web server" <<Apache>> as api_server
        component ":Source code" as source
        component ":Database connection settings" as db_conn
    }
    interface "API endpoints" <<HTTPS>> as endpoints
    interface "Available tests" as tests
    interface "Environment variables" as env
}

component "Functional testing framework" <<Composer package>> as framework {
    component ":Test runner" <<PHP runtime>> as runner
    together {
        component ":Test batch manager" <<PHP runtime>> as manager
        component ":Test database" <<SQLite>> as test_db
        component ":Test class" <<PHP runtime>> as test
        interface "Database connection" as sqlite_conn
        interface "Spawn batch tester" as spawn
        interface "Run tests" as run
    }
}

together {
    component "bouw7" <<Code repository>> as bouw7 {
        component "Database migrations" as migrations
    }
    interface "Pull request" <<SSH>> as bouw7_pull
}

db_conn - env
runner ..( env

bouw7 - bouw7_pull
runner ..( bouw7_pull

endpoints - api_server
test ..( endpoints

tests -- test_cases
tests ). runner

api_server .> source

sqlite_conn - test_db
runner .( sqlite_conn

spawn - manager
runner .( spawn

test - run
run ).. manager
@enduml