@startuml CircleCI Deployment Diagram
left to right direction
skinparam linetype ortho

cloud github as "Github" #line:LightGray;line.dashed {
    storage bouw7 as "Bouw7/bouw7 repository" {
        file frontend as "Frontend Vue.js code"
        file yii2 as "Yii2 code"
        file migrations as "Databasemigraties"
    }

    storage web_api as "Bouw7/web-api repository"{ 
        file api as "Web api code"
    }
}

github -[hidden] CircleCI_cloud

cloud CircleCI_cloud as "CircleCI" #line:LightGray;line.dashed {
    node CircleCI as "CircleCI host" {
        node main as "Main test container" << CircleCi container >> #line:blue;line.dotted;text:blue {
            folder main_artifacts as "CircleCI Artifacts"{
                file func_coverage as "Code coverage output"
            }

            folder main_cache as "CircleCI Cache"{
                storage main_dependencies[
                    Opgeslagen dependencies
                    en packages
                ]
            }

            queue main_workflow [
                .circleci/functional_tests.yml
                ====
                Main testing workflow
            ]

            main_workflow = main_dependencies
            main_workflow = main_artifacts
            main_workflow <== api
        }

        node functional as "Functional test container" << CircleCi container >> #line:blue;line.dotted;text:blue  {
            folder func_artifacts as "CircleCI Artifacts"{
                file func_dummy_data[
                    Database 
                    dummy data
                ]
                file func_results[
                    Testresultaten
                ]
            }

            folder func_cache as "CircleCI Cache"{
                storage func_dependencies[
                    Opgeslagen dependencies
                    en packages
                ]
                folder func_web_api_cache[
                    Cached web-api
                    code files
                ]
                database db_cache[
                    Cached database
                    files
                ]
            }

            folder func_ramdisk as "CircleCI Ramdisk"{
                node func_docker_web_api as "Web-api docker container"
            }

            database func_db as "Lokale database"

            queue func_workflow [
                .circleci/config.yml
                ====
                Functional testing workflow
            ]

            func_workflow == func_db
            func_workflow = func_artifacts
            func_workflow = func_ramdisk
            func_workflow = func_cache
            func_workflow <== api
            func_workflow <== migrations
        }

        folder artifacts as "CircleCI Artifacts"{
            
        }

        folder cache as "CircleCI Cache"{
            
        }

        folder ramdisk as "CircleCI Ramdisk"{

        }

        artifacts --[hidden] cache
        cache --[hidden] ramdisk
    }
}

main --[hidden] functional
@enduml