@startuml Framework class diagram
interface TestCase {
    # Setup() : void
    # Teardown() : void
}
note left
    @Test annotations are used
    to define test functions
    within each TestCase
end note

class TestCaller {
    + Run(argv: string[]) : int
    - SplitBatches(batchesAmount: int, tests: TestCase[], databasePath: string) : 
    - ExecuteBatch()
}


@enduml