@startuml Execute functional tests activity diagram
start

:Scan for php files (recursive);

note right
    Directory to search is given
    as commandline argument to
    framework call.
    Argument 'n' can be given
    to indicate a preferered batch
    size. If n is not given, only
    one batch is spawned.
end note

if (Test found?) then (No: Throw error: "No files found")
    stop
else (Yes)
endif

if (n is defined in call) then (True)
    :Split files into batches of n size;
else (False)
endif

fork
    repeat
        if (File contains @Test annotations) then (False)
            end
            note left
                Skip any file that doesn't
                contain @Test annotated functions;
                continue to next file.
            end note
        else (True)
        endif
        :Execute the test's <i>Setup()</i> method;
        while (Have all tests been run?) is (False)
            :Execute the next <i>@test</i> annotated function;
        endwhile (True) 
        :Execute the test's <i>Teardown()</i> method;
    repeat while (All files in batch tested?) is (False) not (True)
end fork

note right
    This is executed in parallel 
    for all defined batches. 
    If n == 1, execute once.
end note

stop
@enduml