@startuml Execute functional tests activity diagram
start
:Scan for php files (recursive);
note right
    Directory to search is given
    as commandline argument to
    framework call.
end note
if (Test found?) then (False: Throw error: "No files found")
    stop
endif
if (n is defined in call) then (True)
    :Split files into batches of n size;
endif
fork
    repeat
        if (File contains @test annotations) then (True)
            end
            note left
                Skip any file that doesn't
                contain @test annotated functions;
                continue to next file.
            end note
        endif
        :Execute the test's <i>Setup()</i> method;
        while (Have all tests been run?) is (False)
            :Execute the next <i>@test</i> annotated function;
        endwhile (True) 
        :Execute the test's <i>Teardown()</i> method;
    repeat while (All files in batch tested?) is (False) not (True)
end fork
note right
    This is executed in parallel 
    for all defined batches. 
    If n == 1, execute once.
end note
stop
@enduml